name: "Test Docker Compose"

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 7 * * *'
  push:
    branches: [ master, develop, feature/*, fix/* ]
    
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the stack
        run: |
          docker-compose up -d
          sleep 20
          docker-compose logs --tail all litespeed
          docker-compose logs --tail all varnish
          docker-compose logs --tail all haproxy 