name: "Test Docker Compose"

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 7 * * *'
  push:
    branches: [ master, develop, feature/*, fix/* ]
    
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the stack
        run: docker-compose up -d
      - name: Get the logs
        run: docker-compose logs --tail all